#!/bin/bash
d=`date +%y`
m=`date +%b`

if [ "$m" = "Jan" -o "$m" = "Feb" -o "$m" = "Mar" -o "$m" = "Apr" ]
then m="W"
elif [ "$m" = "May" -o "$m" = "Jun" -o "$m" = "Jul" -o "$m" = "Aug" ]
then m="S"
else
m="F"
fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for i in `ls|egrep "^CS [0-9][0-9][0-9]\.pdf$"`; do
mv "$i" "`echo $i | sed "s/^/$m$d\_/; s/\.pdf/\_Notes\.pdf/; s/CS /CS/"`"
done
IFS=$SAVEIFS
